# https://docs.gradle.org/current/userguide/build_environment.html#sec:gradle_configuration_properties
org.gradle.configuration-cache=true

# Maven publication coordinates
# Per AWS SDK plugin guidance: software.amazon.[service].plugin.[pluginname]
group=software.amazon.rolesanywhere.plugin
version=1.0.0
archivesBaseName=roles-anywhere-java-plugin
